apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "proxmox-cert-sync.fullname" . }}
  labels:
    {{- include "proxmox-cert-sync.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronJob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronJob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronJob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronJob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.job.backoffLimit }}
      {{- with .Values.cronJob.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ . }}
      {{- end }}
      template:
        metadata:
          labels:
            {{- include "proxmox-cert-sync.selectorLabels" . | nindent 12 }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: Never
          serviceAccountName: {{ include "proxmox-cert-sync.serviceAccountName" . }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: sync
              image: {{ include "proxmox-cert-sync.image" . | quote }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- with .Values.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                - name: PROXMOX_API_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.proxmox.credentialsSecretName }}
                      key: {{ .Values.proxmox.apiUrlKey }}
                - name: PROXMOX_TOKEN_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.proxmox.credentialsSecretName }}
                      key: {{ .Values.proxmox.tokenIdKey }}
                - name: PROXMOX_TOKEN_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.proxmox.credentialsSecretName }}
                      key: {{ .Values.proxmox.tokenSecretKey }}
                - name: PROXMOX_NODE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.proxmox.credentialsSecretName }}
                      key: {{ .Values.proxmox.nodeNameKey }}
                - name: VERIFY_TLS
                  value: {{ ternary "true" "false" .Values.proxmox.verifyTls | quote }}
                - name: DRY_RUN
                  value: {{ ternary "true" "false" .Values.job.dryRun | quote }}
                - name: MAX_RETRIES
                  value: {{ toString .Values.job.maxRetries | quote }}
                - name: TLS_CERT_KEY
                  value: {{ .Values.certificate.tlsCrtKey | quote }}
                - name: TLS_KEY_KEY
                  value: {{ .Values.certificate.tlsKeyKey | quote }}
                - name: TLS_CA_KEY
                  value: {{ .Values.certificate.caCrtKey | quote }}
                - name: INCLUDE_CA_BUNDLE
                  value: {{ ternary "true" "false" .Values.certificate.includeCaBundle | quote }}
                - name: SERVICES_TO_RESTART
                  value: {{ join "," .Values.servicesToRestart | quote }}
                - name: LOG_FORMAT
                  value: {{ .Values.logging.format | quote }}
                - name: LOG_LEVEL
                  value: {{ .Values.logging.level | quote }}
              {{- with .Values.extraEnv }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.extraEnvFrom }}
              envFrom:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: tls-material
                  mountPath: /certs
                  readOnly: true
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            - name: tls-material
              secret:
                secretName: {{ .Values.certificate.secretName }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
