{{- if .Values.proxmox.createCredentialsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.proxmox.credentialsSecretName }}
  labels:
    {{- include "proxmox-cert-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.proxmox.credentialsData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
