apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-cert-sync
  namespace: proxmox
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: proxmox-cert-sync
      version: "1.2.0"
      sourceRef:
        kind: HelmRepository
        name: proxmox-cert-sync
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      # tag defaults to v{{ .Chart.AppVersion }}
      pullPolicy: IfNotPresent
    proxmox:
      credentialsSecretName: proxmox-credentials
      apiUrlKey: apiUrl
      tokenIdKey: apiTokenId
      tokenSecretKey: apiTokenSecret
      nodeNameKey: nodeName
      verifyTls: true
    certificate:
      secretName: proxmox-certmanager-tls
      tlsCrtKey: tls.crt
      tlsKeyKey: tls.key
      caCrtKey: ca.crt
      includeCaBundle: true
    cronJob:
      schedule: "0 3 1 * *"
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 3
    job:
      dryRun: false
      maxRetries: 1
      backoffLimit: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
